name: bcrypt-benchmarks
version: 0.1

dependencies:
  - base
  - bcrypt
  - bytestring
  - criterion
  - cryptonite

tests:
  bcrypt-equivalent:
    source-dirs: equivalent
    main: Properties.hs
    dependencies:
      - hedgehog
      - tasty
      - tasty-hedgehog
      - tasty-hunit
      - text
  
benchmarks:
  bcrypt-benchmark:
    source-dirs: ./.
    main: Bench.hs
